Milestone :  Created work and about section
Roseokpe/Portfolio pull request #3
Opened 2022-04-27 16:49 UTC by Roseokpe

#Mileston: Portfolio mobile version 2

In this milestone I created the : 
- Work section
- Contact section

2022-04-28 09:36 UTC, CollinsTatang requested changes
Hi @Roseokpe, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## Required Changes ♻️

- [ ] Kindly follow the microverse [README TEMPLATE](https://github.com/microverseinc/readme-template) to update your different readme headers to make your project more readable and professional.

- [ ] You nicely follow the project design and required features but your app is not responsive to mobile screen size.
### **Take a look**
![mobile](https://user-images.githubusercontent.com/55596970/165723772-4752e842-cbcb-4aa8-9716-6efc3a08f5ca.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 09:36 UTC, CollinsTatang commented on index.html
>      </section>
- [ ] Please remove the contact form section from this milestone is not part of the requirement for this milestone.

2022-04-28 09:36 UTC, CollinsTatang commented on style.css
> +  /* padding: 8px 0; */
- [ ] Please remove all commented code from your codebase to make it clean and easy to maintain.

2022-04-30 09:45 UTC, gtekle requested changes
Hi @Roseokpe :wave:, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![this-close](https://user-images.githubusercontent.com/44057863/166100555-363604b3-dd98-4b6f-a94c-4f0d814ef167.gif)


 ## Highlights
:heavy_check_mark: Nice UI
:heavy_check_mark: Good use of Github flow
:heavy_check_mark: Clean code

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] You should add a professional README, as the previous reviewer suggested, based on the [template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided by Microverse. Please, don't remove the sections in the template; even though, you might not have content for each of the at this point in time.
- [ ] You should use both `Grid` and `Flexbox` layout for the works/projects/ section.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 09:45 UTC, gtekle commented on style.css
> +  display: flex;
- [ ] You should use CSS Grid layout for the works container as in the project requirement
![css-grid-flexbox](https://user-images.githubusercontent.com/44057863/166099939-4588e6f1-4de5-4109-a53b-d538d544d2d1.png)
.

2022-04-30 09:45 UTC, gtekle commented on index.html
> +          <h1>MY RECENT <br><br> WORK</h1>
- [ ] You shouldn't use more than one `<h1>` tag in an HTML document for semantic reasons. And you have already used on in the headline section.

2022-04-30 09:45 UTC, gtekle commented on index.html
> +                when an unknown printer took a standard dummy text.
- [ Optional ] You should use a `font-family` of Inter and `font-size` of 20px for the project description text.

2022-04-30 09:45 UTC, gtekle commented on index.html
> +            <h2 class="post-tittle">Multi-Post Stories</h2>
- [ Optional ] You should use a `font-family` of `Roboto` and `font-size` of 32px for the project title text.

2022-04-30 13:00 UTC, OLIPLICHE approved these changes
Hi @Roseokpe, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 14:19 UTC, merged